"""Add password

Revision ID: b55bdad23056
Revises: 37f0d5a7c06e
Create Date: 2024-07-15 21:02:46.462980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55bdad23056'
down_revision = '37f0d5a7c06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_hashed_password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_hashed_password')

    # ### end Alembic commands ###
